### ISSUE TITLE
Set up repo with initial blank React Native project

### ISSUE THREAD

**Issue by ericouyang** [sfbrigade/intentional-walk#1]

**Comment by alexzhues** [comment]
![image](https://user-images.githubusercontent.com/14172178/72859597-4e43d880-3c79-11ea-85fe-c2f14005b5c2.png)

`<iframe src="https://giphy.com/embed/9K2nFglCAQClO" width="480" height="204" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/9K2nFglCAQClO">via GIPHY</a></p>`

**Comment by alexzhues** [comment]
![itsworking](https://user-images.githubusercontent.com/14172178/72859723-abd82500-3c79-11ea-8d82-75e6262cc6b3.gif)

**Comment by ericouyang** [comment]
Awesome work, @alexzhues!
