### ISSUE TITLE
CHINESE VERSION - Privacy policy wording update

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#107]
The character right after "Intentional Walk" in item 12 of the privacy policy should be changed to: 計

See full text below: 
_12.如果您對Intentional Walk**計**劃或應用程序有任何疑問或意見，請通過以下方式與SFDPH聯繫：intentionalwalk@sfdph.org或CDPH隱私權辦公室：Privacy@cdph.ca.gov。_

**Comment by francisli** [comment]
Did the privacy policy change? Where's the source doc

There's currently _11_ items in the Privacy Policy, and the character after Intentional Walk in item 11 _does_ match the character noted above, although the characters _before_ Intentional Walk appear to be different....

**Comment by brittmj** [comment]
It seems like GitHub maybe copied the character in a strange way.  The source doc is [here](https://docs.google.com/presentation/d/1P8lKNPcFYsKGEQFz5K2_BQZLAFZVw4XmqN1O_o8zses/edit#slide=id.g82b31645ec_1_38).  Slide 73-74.  I don't think the privacy policy has changed since it was originally translated.

**Comment by francisli** [comment]
Got it. It's the character right _before_ Intentional Walk that has changed... and, now I remember, if you look in the source doc, they all skipped #9 which is why we don't have an item 12 in our app files...
