### ISSUE TITLE
User sees "total steps this month" rather than "overall step total" on main step dashboard (DON'T CHANGE UNTIL AFTER JUNE 15)

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#114]
![Home - _total steps this month_](https://user-images.githubusercontent.com/42448914/82493556-03a66180-9a9d-11ea-9412-ab7434b0947c.png)

**Comment by francisli** [comment]
So, with the changes I've made, the box subtitle will be "overall step count" when a contest is active, and "total steps this month" (needs translations) when NOT in a contest period. And the counts will reflect those date ranges (i.e. start of contest until now for contest, start of month until now for outside contest dates).
