### ISSUE TITLE
Home screen bottom margin is a bit large on Samsung Galaxy S3

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk#123]
![Screenshot_2020-06-17-16-08-31](https://user-images.githubusercontent.com/140766/84959856-12406280-b0b5-11ea-8a67-0dfb8810e614.png)

@brittmj Right now, the bottom button perfectly covers up the Recorded Walks section. Adding maybe just a slight transparency would also provide the hint that there's more to scroll/see?

**Comment by brittmj** [comment]
Oh yeah, that's no good.  I think a slightly transparent gradient would work really well.  Let me try it out in Figma.
