### ISSUE TITLE
Change dates anywhere it says July 1 or July 31 to September 1 and September 30 respectively 

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#136]

**Comment by brittmj** [comment]
@francisli do we need translations of September 1 and September 30?

**Comment by francisli** [comment]
We should not need translations of the dates. A localized date library is used in the app to generate date strings.

To test this now, we can create a new "Contest" in the server with those dates. The interface for that is here:

https://iwalk-test.c4sf.me/admin/home/contest/

If we set the "promo date" for the new contest to today or earlier, then that should trigger the app on the next launch to start displaying the new, upcoming contest dates and message prompts.

Let me know if you want me to do this now. Or you may want to do this to add to any documentation you're collecting on how we manage the service.

@ericaeilenberg

**Comment by ericaeilenberg** [comment]
Hi Francis,

Might as well change it now? I can’t think of any harm in doing that. Also seems pretty straight forward. I’ll check out the link below.

Erica

Sent from my iPhone

On Jul 13, 2020, at 1:15 PM, Francis Li <notifications@github.com> wrote:

﻿

We should not need translations of the dates. A localized date library is used in the app to generate date strings.

To test this now, we can create a new "Contest" in the server with those dates. The interface for that is here:

https://iwalk-test.c4sf.me/admin/home/contest/

If we set the "promo date" for the new contest to today or earlier, then that should trigger the app on the next launch to start displaying the new, upcoming contest dates and message prompts.

Let me know if you want me to do this now. Or you may want to do this to add to any documentation you're collecting on how we manage the service.

@ericaeilenberg<https://github.com/ericaeilenberg>

**Comment by brittmj** [comment]
Yes, thanks Francis.  I just did a test one to start promoting today, start
the competition tomorrow, and end the competition friday.  Looks like it's
working! Erica, feel free to override that if you want to put in the real
competition dates, I just wanted to test it out.

Britt
