### ISSUE TITLE
Update translation of "total steps this month" in spanish and chinese

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#137]
Spanish: 12,839 pasos totales este mes

Chinese: 今月的總步數12,839 

<img width="203" alt="Screen Shot 2020-07-13 at 12 20 52 PM" src="https://user-images.githubusercontent.com/42448914/87344451-503d7480-c503-11ea-8bf8-a5aabd72fa5b.png">

**Comment by francisli** [comment]
Spanish previously updated in commit #134
