### ISSUE TITLE
Edit Contest rules for the 2021 Intentional Walk contest

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk#158]
This file has stale information: https://github.com/sfbrigade/intentional-walk/blob/master/assets/contestRules/contestRules.en.txt

The following edits need to be made:
*Starts on August 1, 2021, at 12:00 AM PST.
*Ends at 11:59 p.m. PST on August 31, 2021.
*The top ten walkers will be notified the first week of September 2021 by email.

**Comment by francisli** [comment]
Updating this in the codebase is definitely the first and quickest way to change this...

If there's time, we could consider pushing this content to the server to be fetched and displayed. Especially since contest start/end dates are managed in the back-end...

**Comment by jeaninesw** [comment]
@KelsMarie Don't the rules also need to be updated in the other two languages besides English? I can manage the Spanish one, but I'll likely need help with the Chinese one.
