### ISSUE TITLE
Django: All walks download incorrectly downloads daily walks should download all walks

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk#162]
In Django https://iwalk-test.c4sf.me/, when downloading **all walks**, the incorrect file (daily walks) downloads, and we want **all walks** to be the file downloaded. 
The CSV file is not able to filter.

<img width="1071" alt="Screen Shot 2021-06-09 at 11 32 27 AM" src="https://user-images.githubusercontent.com/55925894/121418621-fcf4c180-c91f-11eb-9590-f6e64ca360bf.png">

**Comment by ohrite** [comment]
@KelsMarie I've moved this to the Django application: https://github.com/sfbrigade/intentional-walk-server/issues/37
