### ISSUE TITLE
Year in App Sept 2020

### ISSUE THREAD

**Issue by gregboyer** [sfbrigade/intentional-walk#182]
"One thing I notice is the contest rules are changed to reflect Aug 1-31, 2021, but throughout the app I still see Sept 2020 dates" - Per Erica

**Comment by francisli** [comment]
I checked the server and the new Contest record, and it looked fine- the issue with the dates in the app is that the Start Promo date for the new contest was set for July 5, so it was not going to start showing details about the new contest until then... I just backed up the start promo date to June 29, so everyone who re-opens the app now (and gives it a second to refresh) should now see the new contest promo banner and all the correct dates throughout the rest of the app...
