### ISSUE TITLE
Android & IOS Contest Dates Sept 1, 2021 - Sept 30, 2021

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk#194]
Android and IOS devices still show August contest dates. Needs to be September 1, 2021 - September 30, 2021.

**Comment by jeaninesw** [comment]
I'm blocked on this issue until we have translated verbiage to change the following text with something that will work for all dates:
> The top ten walkers will be notified the first week of September 2021 by email.
