### ISSUE TITLE
Get and display passive steps from operating system

### ISSUE THREAD

**Issue by ericouyang** [sfbrigade/intentional-walk#2]

**Comment by francisli** [comment]
@alexzhues in #4 you mentioned using the Pedometer library from Expo: 

https://docs.expo.io/versions/latest/sdk/pedometer/

Which also has additional dependencies for installation (i.e. the unimodules library).

It might be worth also exploring using a library with fewer dependencies, like this one:

https://github.com/OvalMoney/react-native-fitness

If you want to do some parallel research, we can each pull off a branch of the repo to test one or the other...?

If you want to experiment with the Expo pedometer library, I can try the react-native-fitness library...

**Comment by francisli** [comment]
@ericouyang I've reconfigured the iOS app to use the bundle identifier you created in the new team account, and everything is working well. I've updated the branch in the associated PR accordingly and will be working on setting up Android next.

FYI, I'll be updating the instructions for setting up the Android environment on Mac OS X- there should be no need to install another copy of the JDK with Homebrew if you've first installed Android Studio, as you can reference the version of Java bundled into it. Also, I'm not sure how you ran the build without also setting up some other environment variables (i.e. ANDROID_SDK_HOME), which I'll also add into the README...?

Next time, can you open a PR before merging changes onto master branch for review? Maybe we should protect master branch, and set some branch/PR commit conventions- I like to have every commit on master branch tagged with a corresponding issue id describing what it does, so it's always easy to look back at any additional details/conversation regarding every commit. You can see this in my last commit on master branch in the commits tab- Github automatically creates a link back to the issue if you add it to the commit message. It makes for a nice, clean commit history that can be used to automatically generate version/release notes for every build.

**Comment by francisli** [comment]
At this time, I am able to successfully request permissions and fetch step count info on iOS using react-native-fitness. On Android, I am able to successfully request permissions, and "subscribe" to record activity, but as of yet have not been able to actually get any actual step data. Although my primary phone is iOS, I will try to carry my test Android phone with me to see if that changes.

I took a quick peek at the Expo Pedometer library code. It is actually incomplete, and does not properly support Android at this time. You can see the TODO here:

https://github.com/expo/expo/blob/a30854cccc4233162ca7b308db6f41a7dbfc2429/packages/expo-sensors/android/src/main/java/expo/modules/sensors/modules/PedometerModule.java#L73

As a result, I'm going to move forward with react-native-fitness, and close this issue.
