### ISSUE TITLE
User can see text in different languages

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk#21]
Before we get too far prototyping the screens and putting text directly into the views, we should just plan now to incorporate a localization file with all the strings.

Here's one library that I've used in a previous project:

https://www.npmjs.com/package/react-native-localization

However, if you are aware of a different/better solution, you are welcome to integrate it as long as it allows us to easily translate all the text in a single location.

**Comment by brittmj** [comment]
Erica has finalized the text in English and this week I'm going to set up a document that will allow her translators to easily update the text.  Should have translations within a week or two.

**Comment by francisli** [comment]
@drumwolf per @ericouyang comment in your prior PR, do you want to take on the task of setting up the app for localization?

I've linked a commonly used localization library above that can be used...

**Comment by francisli** [comment]
Majority of work is done, closing as completed, will open new issues for specific updates/changs/bugs.
