### ISSUE TITLE
Server baseURL should depend on environment

### ISSUE THREAD

**Issue by lee51** [sfbrigade/intentional-walk#211]
We should check environment/configuration variables and set the server `baseURL` accordingly.
Development should generally be done against the staging server address, not prod.

**Comment by francisli** [comment]
We should be able to use this dotEnv package to parameterize the baseURL variable in the Api file.

https://www.npmjs.com/package/react-native-dotenv

Then we will need to do some testing to see how we can coordinate with the fastlane build scripts to change the env to a different setting when building test (staging) and release (production) apps.

**Comment by francisli** [comment]
Still need to do work to update Fastlane scripts to apply appropriate env on build

**Comment by francisli** [comment]
For now, manually copying one of the .env.* files to .env before running fastlane is sufficient to set the environment for the build
