### ISSUE TITLE
Record a Walk button icons missing on Galaxy Note 20

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk#271]
https://user-images.githubusercontent.com/140766/228711772-fb31fe0c-1dbe-47d2-9c2f-af72bd82150d.mp4

**Comment by francisli** [comment]
Expected:

![Screenshot_20230329-194842542](https://user-images.githubusercontent.com/140766/228719037-4db1e809-2b07-4599-8271-38ad291d9cae.jpg)

**Comment by Lckythr33** [comment]
Closed, glitch due to conflicting versions.
