### ISSUE TITLE
If user has recorded walks they will be able to see the most recent 2 walks on the home page

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#28]
![Home - Recorded Walks](https://user-images.githubusercontent.com/42448914/74366148-4b259f00-4d84-11ea-9dd9-da5fb357951a.png)

**If the user hasn't recorded walks, they will see this:** 
![Home - No Walks](https://user-images.githubusercontent.com/42448914/74366138-482aae80-4d84-11ea-852f-4778bd71d0dc.png)

**Comment by francisli** [comment]
Closing as completed, will open new issues for specific bugs/changes needed.
