### ISSUE TITLE
User should be able to pull-to-refresh on Leaderboard

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk#280]

**Comment by markkhoo** [comment]
Pull-to-refresh [docs](https://reactnative.dev/docs/0.64/scrollview#refreshcontrol) for React Native.

**Code Snippet:**
```js
import React, { useState } from 'react';
import { ScrollView, RefreshControl } from 'react-native';

const App = () => {
  const [refreshing, setRefreshing] = useState(false);

  const onRefresh = () => {
    setRefreshing(true);
    // Perform the data fetching or other operations
    // that you want to perform when the user refreshes.
    // Once the operation is complete, set the refreshing
    // state back to false to hide the indicator.
    setTimeout(() => {
      setRefreshing(false);
    }, 2000);
  };

  return (
    <ScrollView
      refreshControl={
        <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
      }
    >
      {/* Add your scrollable content here */}
    </ScrollView>
  );
};

export default App;
```
In this example, we're using the ScrollView component as the scrollable view and passing the RefreshControl component as a prop to the ScrollView. The refreshing prop of the RefreshControl component is used to indicate whether the refresh indicator should be visible or not. The onRefresh prop is used to handle the refresh event and perform the necessary operations.

When the user pulls down on the ScrollView, the onRefresh function is called, which sets the refreshing state to true. You can perform the data fetching or other operations that you want to perform when the user refreshes in this function. Once the operation is complete, set the refreshing state back to false to hide the indicator.

Note that the RefreshControl component only works with scrollable components like ScrollView, FlatList, and SectionList. It doesn't work with non-scrollable components like View or Text.
