### ISSUE TITLE
User is able to start recording an new walk from the home page if they click "Record New Walk"

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#29]
**Once they click record, this page pops up for entire duration of walk**
![Recording Walk - Recording](https://user-images.githubusercontent.com/42448914/74366230-73150280-4d84-11ea-806c-ac2329ef8731.png)

**Comment by francisli** [comment]
Closing as completed, will open new issues for specific bugs/changes needed.
