### ISSUE TITLE
Chinese Translation - Updated

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk#301]
<img width="490" alt="Screen Shot 2023-04-26 at 4 15 40 PM" src="https://user-images.githubusercontent.com/55925894/234719407-7788022c-e986-4122-9749-44ceaab24c9a.png">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?node-id=4540%3A3211&t=1SN4c9aKqNy5grK8-1](url)

**Comment by Lckythr33** [comment]
Can I please have them in text to copy paste into the translations

**Comment by Lckythr33** [comment]
Disregard i got them from Figma , Sorry!
