### ISSUE TITLE
Spanish Translation - Updated

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk#302]
<img width="499" alt="Screen Shot 2023-04-26 at 4 17 52 PM" src="https://user-images.githubusercontent.com/55925894/234719746-c16a37e1-72c8-4803-8fca-1c3dd2c8f35a.png">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?node-id=4541%3A3359&t=1SN4c9aKqNy5grK8-1](url)

**Comment by KelsMarie** [comment]
The Spanish and Chinese translations are the final version updated with "Explore Nature." Thank you all!

**Comment by Lckythr33** [comment]
Committed to branch, will create PR when #301 is updated
