### ISSUE TITLE
User is able to stop a walk once they're done recording and has to acknowledge they're done before it saves

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#31]
If they click stop/save, they end up on this page and have to click "finish"

![Recording Walk - Saving](https://user-images.githubusercontent.com/42448914/74366364-bec7ac00-4d84-11ea-85e6-e2583c02340a.png)

**Comment by francisli** [comment]
Closing as completed, will open new issues for specific bugs/changes needed.
