### ISSUE TITLE
User can choose their language at the start of onboarding

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#36]
Start button appears in whatever language they've chosen once they've selected their language

![Onboarding - Language Choice](https://user-images.githubusercontent.com/42448914/74368055-be7ce000-4d87-11ea-8864-b4a6696d3bdc.png)

![Onboarding - Lanugage English](https://user-images.githubusercontent.com/42448914/74368052-bd4bb300-4d87-11ea-889e-bac4b610b565.png)

**Comment by francisli** [comment]
Closing as completed, will open new issues for specific bugs/changes needed.
