### ISSUE TITLE
Find accommodations for iOS Development

### ISSUE THREAD

**Issue by alexzhues** [sfbrigade/intentional-walk#4]
Without a mac, I don't have a way to develop this app for iOS. 

One idea is to develop this first for android, then maybe spend a weekend with my roommate's mac porting everything over. I'll worry about this later though

**Comment by alexzhues** [comment]
Update: 
This project is currently using the following npm package: https://docs.expo.io/versions/latest/sdk/pedometer/

Per documentation, this dependency must also be installed & configured for iOS
https://github.com/unimodules/react-native-unimodules

**Comment by francisli** [comment]
Hi @alexzhues, I'll spend some time in the next week to test the codebase on iOS, so feel free to just focus on Android development...

Per the pedometer library integration, let's pick that up in the relevant corresponding story...
