### ISSUE TITLE
User can navigate to Program Sponsors screen from hamburger menu

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk#63]
<img width="228" alt="Screen Shot 2020-03-28 at 11 51 22 PM" src="https://user-images.githubusercontent.com/140766/77843154-20828080-714f-11ea-8e74-cc0d7940640c.png">

@brittmj which of the designs in Figma is the final approved Program Sponsors screen?

**Comment by brittmj** [comment]
@francisli sorry, somehow didn't see your tag and question about final sponsors page.  Just opened an issue about designing the sponsors page.  That issue has the final design.  The figma file has also been cleaned up so only the final design is present.

**Comment by francisli** [comment]
Closing, replaced by #69
