### ISSUE TITLE
Recorded Walk component layout not fixed/consistent with varying text strings

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk#66]
![IMG_1135](https://user-images.githubusercontent.com/140766/78194442-02a86a80-7432-11ea-8325-739957b4679b.PNG)

**Comment by francisli** [comment]
@santiagogomezl this is a pretty minor cosmetic issue, but might be a way to jump in to the mobile app codebase...?

**Comment by santiagogomezl** [comment]
Currently reviewing...

**Comment by santiagogomezl** [comment]
Pushed element to the right side and aligned '|' marker across all View components

![Screen Shot 2020-06-25 at 3 26 43 PM](https://user-images.githubusercontent.com/63277146/85821690-0a746400-b72e-11ea-842d-37663107c7c1.png)
<img width="287" alt="Screen Shot 2020-06-25 at 9 28 04 AM" src="https://user-images.githubusercontent.com/63277146/85821691-0b0cfa80-b72e-11ea-862c-11abbb1de34f.png">
