### ISSUE TITLE
Opening screen needs new logo (see image in comments)

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#87]
![Onboarding - Splash Page](https://user-images.githubusercontent.com/42448914/79413689-792e8780-7f5d-11ea-8e4d-6e54cce1330a.png)

**Comment by francisli** [comment]
If you're seeing the old splash screen logo on iOS, it's because the operating system caches the image from the previous installation.

Delete the app. Restart your device completely (power off, then on). Then, re-install.
