### ISSUE TITLE
SPANISH VERSION - Translate Email Required pop-up in sign-in flow (translation in comment below)

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#99]
Correo electrónico.

Por favor, introduce una dirección de correo electrónico válida. 

Está bien

**Comment by francisli** [comment]
FYI I've copied the text as shown in this issue, but note that the alert title simply says "Email" in Spanish, not "Email Required", like it does with the spanish translation of "Zip Code Required" in #98.
